### PR TITLE
Material ui update

### PR DESCRIPTION
**Pull request by seleregb**
Updated material update with no breaking changes hopefully  

#17

### CODE REVIEW

**Comment by devshawn** [comment]
Thanks for doing this! I'll check this out tomorrow and get it merged.

**Comment by seleregb** [comment]
> Thanks for doing this! I'll check this out tomorrow and get it merged.

sure. 😄

**Comment by devshawn** [comment]
Hey @seleregb - can you resolve conflicts? Then I can merge :)

**Comment by seleregb** [comment]
> Hey @seleregb - can you resolve conflicts? Then I can merge :)

I've resolved the conflicts

**Review by devshawn — APPROVED** [review]

**Pull request merged**
