### PR TITLE
Upgrade to latest babel version and move from es2015 to env preset

### PR DESCRIPTION
**Pull request by josecolella**
- Upgraded to Babel version 7
- Moved from es2015 to env-preset
- All test pass locally

### CODE REVIEW

**Comment by josecolella** [comment]
References Issue https://github.com/devshawn/password.live/issues/18

**Comment by josecolella** [comment]
@devshawn  Can you merge this PR?

**Comment by devshawn** [comment]
Looks great -- nice job!

**Comment by devshawn** [comment]
Thanks for the contribution! 👍

**Pull request merged**
